name: salary_calc
description: 연봉계산기 - 실수령액 계산

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.1+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  another_flushbar: ^1.10.28
  awesome_dropdown: ^0.0.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  vibration: ^1.7.4-nullsafety.0
  money_formatter: ^0.0.3 # flutter_money_formatter --> money_formatter 로 교체
  #flutter_money_formatter:
  #  git:
  #    url: git://github.com/anisalibegic/flutter_money_formatter.git
  # https://github.com/fadhly-permata/flutter_money_formatter/issues/25
  # flutter_money_formatter: ^0.8.3 
  
  shimmer: ^2.0.0  
  get: ^4.6.1
  package_info: ^2.0.2
  settings_ui: ^2.0.1
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^9.2.0
  expandable: ^5.0.1
  share: ^2.0.4
  url_launcher: ^6.0.18
  flip_card: ^0.6.0
  fl_chart: ^0.41.0  
  lazy_data_table: ^0.3.1
  awesome_dialog: ^2.1.2
  flutter_jk:
    git:
      url: https://github.com/smok95/flutter_jk.git
      ref: 9ccbfaa88ef628313782a10c25b95d67e17d6dd0 # 1.11.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
